### ISSUE TITLE
Existence of étée,étées and étés

### ISSUE THREAD

**Issue by gabsens** [stopwords-iso/stopwords-fr#3]
I'm trying to understand why the list contains the stopwords `étée, étées, étés`. According to the Bescherelle (the reference for verbs' conjugaison), the participe passé of the verb `être` is *invariable*. In other words, `étée, étées, étés` do not exist.

**Comment by TitouanT** [comment]
You are right on the fact that they do not exist in the french's correct set of words but they do appear in other sets of data because they are common misspelled version of "été". Therefore, being able to filter them out is a good thing.

**Comment by genediazjr** [comment]
Thanks @TitouanT for pointing it out. Hope it helps @gabsens!
