### ISSUE TITLE
L412

### ISSUE THREAD

**Issue by tianpu** [stopwords-iso/stopwords-fr#4]
> o|

| is not a letter

**Comment by genediazjr** [comment]
sorry for the very late response. is it possible that this is an encoding issue?

**Comment by tianpu** [comment]
Hello there,
I open the file in hex editing mode, and could see the character is "7C", so it should be "|".
I know little about french, if there is such grammar/usage, should be okay.
Because "|" is a reserved keyword of Regular Expressions, so sometimes would be an issue if not be careful.
